### ISSUE TITLE
Cant install on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by mikesparr** [TAKEALOT/nodervisor#38]
Looking forward to checking this out. Great job!

Cloned repo on a Linux server, cd to directory and ran `npm install` and failed. Tried `sudo npm install` as well and also failed. If I can figure out I'll share but below is console output on failed install in case you have ideas.

~~~
sudo npm install
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.7 install /usr/share/nodervisor/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/bin/nodejs --eval require('/usr/share/nodervisor/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node')
/usr/bin/nodejs: symbol lookup error: /usr/share/nodervisor/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile 
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/share/nodervisor/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static void node_sqlite3::Database::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/database.cc:134:71: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>, v8::PropertyAttribute)’
     args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
                                                                       ^
../src/database.cc:134:71: note: candidates are:
In file included from /home/ubuntu/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/database.cc:2:
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
   bool Set(Handle<Value> key, Handle<Value> value);
        ^
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note:   candidate expects 2 arguments, 3 provided
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   bool Set(uint32_t index, Handle<Value> value);
        ^
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
../src/database.cc:135:69: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Integer>, v8::PropertyAttribute)’
     args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
                                                                     ^
../src/database.cc:135:69: note: candidates are:
In file included from /home/ubuntu/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/database.cc:2:
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
   bool Set(Handle<Value> key, Handle<Value> value);
        ^
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note:   candidate expects 2 arguments, 3 provided
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   bool Set(uint32_t index, Handle<Value> value);
        ^
/home/ubuntu/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory `/usr/share/nodervisor/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/usr/share/nodervisor/node_modules/sqlite3/lib/binding/node-v14-linux-x64" "--remote_path=./sqlite3/v2.2.7/" "--package_name=node-v14-linux-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz"
gyp ERR! cwd /usr/share/nodervisor/node_modules/sqlite3
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/share/nodervisor/node_modules/sqlite3/lib/binding/node-v14-linux-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/share/nodervisor/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.13.0-24-generic
node-pre-gyp ERR! command "node" "/usr/share/nodervisor/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/share/nodervisor/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/share/nodervisor/node_modules/sqlite3/lib/binding/node-v14-linux-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz' (1)
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/nodervisor/npm-debug.log
~~~

**Comment by mikesparr** [comment]
Looks like same issue in #36 as well.

**Comment by mikesparr** [comment]
Edited the package.json file and just removed the specific version number for sqllite3 and install works.
