### ISSUE TITLE
Unable to install (bcrypt, node-gyp rebuild...  shared_ptr.h:146: error: cannot use typeid with -fno-rtti)

### ISSUE THREAD

**Issue by RobinAllen** [TAKEALOT/nodervisor#47]
```
$npm install
npm WARN deprecated connect@2.11.0: connect 2.x series is deprecated
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> bcrypt@0.8.0 install /login/xxxxxxxx/nodervisor-installation/nodervisor-master/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/login/xxxxxxxx/nodervisor-installation/nodervisor-master/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:21,
                 from /login/xxxxxxxx/.node-gyp/8.7.0/include/node/node.h:63,
                 from ../../nan/nan.h:23,
                 from ../src/bcrypt_node.cc:31:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /login/xxxxxxxx/.node-gyp/8.7.0/include/node/node.h:63,
                 from ../../nan/nan.h:23,
                 from ../src/bcrypt_node.cc:31:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: At global scope:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:333: error: expected unqualified-id before ‘using’
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:350: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:357: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:365: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:394: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:396: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:401: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:775: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:800: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:812: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: At global scope:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:838: error: expected unqualified-id before ‘using’
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:1187: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:1193: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:1733: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: At global scope:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:3198: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:3839: error: ‘nullptr’ was not declared in this scope
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h: At global scope:
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:4108: error: function definition does not declare parameters
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:4164: error: expected unqualified-id before ‘&’ token
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:4164: error: expected ‘)’ before ‘&’ token
/login/xxxxxxxx/.node-gyp/8.7.0/include/node/v8.h:4164: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from ../../nan/nan.h:29,
                 from ../src/bcrypt_node.cc:31:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/login/xxxxxxxx/nodervisor-installation/nodervisor-master/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/login/xxxxxxxx/nodervisor-installation/node-v8.7.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-696.13.2.el6.x86_64
gyp ERR! command "/login/xxxxxxxx/nodervisor-installation/node-v8.7.0-linux-x64/bin/node" "/login/xxxxxxxx/nodervisor-installation/node-v8.7.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /login/xxxxxxxx/nodervisor-installation/nodervisor-master/node_modules/bcrypt
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN sqlite3@2.2.7 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by RobinAllen** [comment]
Both bcrypt and later sqlite3 failed to install correctly with the default install.
I successfully worked around these issues, by modifying package.json to use "bcrypt": "^1.0.3" and "sqlite3": "^3.1.13".
